name: FlashMaple Web CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Check out repository
        uses: actions/checkout@v4

      - name: ☕️ Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.14.1'
          cache: 'yarn'

      - name: 📦 Install dependencies and build
        env:
          NEXT_PUBLIC_API_ORIGIN: ${{ vars.NEXT_PUBLIC_API_ORIGIN }}
          SITE_URL: ${{ vars.SITE_URL }}
          NEXT_PUBLIC_GOOGLE_OAUTH_CLIENT_ID: ${{ vars.NEXT_PUBLIC_GOOGLE_OAUTH_CLIENT_ID }}
          NEXT_PUBLIC_FUSIONAUTH_AUTHORIZATION_ENDPOINT: ${{ vars.NEXT_PUBLIC_FUSIONAUTH_AUTHORIZATION_ENDPOINT }}
          NEXT_PUBLIC_FUSIONAUTH_CLIENT_ID: ${{ vars.NEXT_PUBLIC_FUSIONAUTH_CLIENT_ID }}
          NEXT_PUBLIC_FUSIONAUTH_GOOGLE_IDP_ID: ${{ vars.NEXT_PUBLIC_FUSIONAUTH_GOOGLE_IDP_ID }}
          NEXT_PUBLIC_COOKIE_DOMAIN: ${{ vars.NEXT_PUBLIC_COOKIE_DOMAIN }}
        run: yarn install --frozen-lockfile && yarn build:prod 

      - name: 🐳 Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo tee /etc/apt/trusted.gpg.d/docker.asc
          echo "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/docker.asc] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io

      - name: 📦 Build Docker image
        run: docker build -t flashmaple-web:latest -f Dockerfile .

      - name: 📤 Transfer image and restart Docker
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY}}
          SSH_SERVER_IP: ${{ secrets.SSH_SERVER_IP }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key && chmod 600 private_key
          mkdir -p ~/.ssh
          ssh-keyscan -H ${SSH_SERVER_IP} >> ~/.ssh/known_hosts
          
          # Save the Docker image.
          echo "Saving new flashmaple-web.tar..."
          docker save flashmaple-web:latest -o flashmaple-web.tar
          
          # Upload the image to the server.
          echo "Uploading compressed flashmaple-web.tar to server..."
          scp -i private_key flashmaple-web.tar ${SSH_USERNAME}@${SSH_SERVER_IP}:/www/wwwroot/flashmaple
          echo "File upload completed successfully."
          
          # Restart the remote container.
          echo "Restart docker server..."
          ssh -i private_key ${SSH_USERNAME}@${SSH_SERVER_IP} << EOF
            cd /www/wwwroot/flashmaple
          
            # Remove the existing container.
            docker stop flashmaple-web || true
            docker rm flashmaple-web || true

            # Load the new image.
            docker load -i flashmaple-web.tar
          
            # Run on port 8085 in the baota_net network.
            docker run -d --name flashmaple-web --restart unless-stopped --network baota_net -p 8085:8085 -v /www/wwwroot/flashmaple/logs:/app/logs flashmaple-web:latest
            
            # Remove unused images.
            docker image prune -f
          EOF
          echo "Restart docker completed successfully."
